### ISSUE TITLE
laravel-admin在回调函数的一个问题。

### ISSUE THREAD

**Issue by haipersist** [z-song/laravel-admin.org#22]
laravel-admin在回调函数的一个问题。

在edit页面，调用form->saving回调函数时，遇到一个问题：

如果在函数里用了dump方法来获取提交的数据后，后续再用redirect，并不能正常重定向目标地址。
```php 
$form->saving(function (Form $form){
                $account_order_id = $form->model()->account_order_id;
                $new_status = dump($form->status);
                  .......

            });
              return redirect('bankstatment_list/')->with(compact('success'));
}
```
利用F12调试发现，发起post请求后，系统又发起了一个当前页面的get请求，并没有直接跳转到目标地址。

http://localhost:8000/bankstatment_list/4164  post

http://localhost:8000/bankstatment_list/4164  get

**Comment by z-song** [comment]
重定向不是应该放在saving回调里面吗？

**Comment by BrothelUndercover** [comment]
laravel-admin grid列操作的editable组件,不知道有没有提供回调的操作(比如更新某个字段的同时还需去做一些操作)
