### ISSUE TITLE
method "expand" in column object is in the demo , but can't find it in the files

### ISSUE THREAD

**Issue by amjadmasri** [z-song/laravel-admin.org#23]
in the demo inside the user grid , there is a column with the feature to expand and view a table with the profile information inside it , I tried to use the same code and it is giving me a null cell in the column
![image](https://user-images.githubusercontent.com/26228083/38138228-fc1abcee-3429-11e8-82b0-963f3ec31c83.png)
 , and I can't find any method inside the column.php file called "expand" . was this functionality removed ? 
if it was what can I do to mimic the same behavior without using the expand method.

**Comment by z-song** [comment]
Its' a column extension, at first add this extension [ExpandRow.php](https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Extensions/ExpandRow.php),  then register this in [bootstrap.php](https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/bootstrap.php)

```php
use Encore\Admin\Grid\Column;
use App\Admin\Extensions\Column\ExpandRow;

Column::extend('expand', ExpandRow::class);
```

Now you can use this feature now

**Comment by bmwael** [comment]
use App\Admin\Extensions\ExpandRow; 
instead of use App\Admin\Extensions\Column\ExpandRow;
