### ISSUE TITLE
dateRange datetimeRange, timeRange如何设置默认值？

### ISSUE THREAD

**Issue by denghp** [z-song/laravel-admin.org#28]
请问，这三个范围组件dateRange datetimeRange, timeRange 如何像当个组件一样设置默认值呢？
e.g.:
```
$form->date("created_time", '创建日期')->default("2018-04-20");
```

**Comment by z-song** [comment]
```php
$form-> dateRange("created_time", '创建日期')->default(['start' => "2018-04-20", 'end' => '"2018-04-20"']);
```

**Comment by denghp** [comment]
$form->dateRange("date_start","date_end","创建日期范围")->default(['start'=> "2018-04-20",'end'=> "2018-04-28"]);

我是这么写的代码，但是无效。
php.version : 7.1.14
laravel-admin:"1.5.*",
Laravel Framework 5.6.12

@z-song
