### ISSUE TITLE
Demo_Source_Code Demo-Posts can't run normally, Sir

### ISSUE THREAD

**Issue by hbkq110** [z-song/laravel-admin.org#35]
![Uploading image.png…]()
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait 'Encore\Admin\Controllers\HasResourceActions' not found

**Comment by hbkq110** [comment]
The lacked file (HasResourceActions) has been copied from laravel-admin folder.  But another issue occur as below:

Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Encore\Admin\Grid::__toString() must not throw an exception, caught TypeError: Argument 1 passed to Encore\Admin\Grid\Filter\Where::__construct() must be an instance of Closure, string given, called in E:\DD\laravel_admin_demo\vendor\encore\laravel-admin\src\Grid\Filter.php on line 303"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalErrorException in E:\DD\laravel_admin_demo\vendor\encore\laravel-admin\src\Layout\Column.php:0

**Comment by hbkq110** [comment]
Cannot use object of type Encore\Admin\Grid\Tools\BatchDelete as array (View: E:\DD\laravel_admin_demo\vendor\encore\laravel-admin\resources\views\grid\batch-actions.blade.php) (View: E:\DD\laravel_admin_demo\vendor\encore\laravel-admin\resources\views\grid\batch-actions.blade.php)

**Comment by hbkq110** [comment]
<ul class="dropdown-menu" role="menu">
        @foreach($actions as $action)
            <li><a href="#" class="{{ $action->getElementClass() }}">{{ $action->getTitle() }}</a></li>
        @endforeach
    </ul>

**Comment by z-song** [comment]
Run` composer update`,  make sure that you are using the latest `1.5.x-dev` version of larave-admin.

**Comment by z-song** [comment]
You'd better clone this repo and reinstall it, don't just use git pull to update.

**Comment by hbkq110** [comment]
Thanks, it's done now.

**Comment by space-blank** [comment]
The lacked file (HasResourceActions) has been copied from laravel-admin folder?
Where does it copy from? I didn't find

**Comment by z-song** [comment]
@space-blank Clone this repo and reinstall

**Comment by space-blank** [comment]
v1.5.8和master分支上的代码不一样, 重新安装也是缺少这个文件

**Comment by z-song** [comment]
@space-blank 这个demo依赖的laravel-admin版本是`1.5.x-dev`, `1.5.x-dev`对应master分支

**Comment by DudleyDawson** [comment]
I'm trying to update an old codebase with the latest laravel-admin and still seeing this. I have confirmed that HasResourceActions is present in vendor/encore/laravel-admin/src/Controllers, what can I do to fix this?  I'm currently configuring composer like so:
`"encore/laravel-admin": "^1.6"`
