### ISSUE TITLE
Extension not found 

### ISSUE THREAD

**Issue by JackKuo-tw** [z-song/laravel-admin.org#36]
您好，我按照[這篇](https://github.com/z-song/laravel-admin.org/blob/master/public/docs/v1.4/zh/model-grid-custom-tools.md) 教程的 UserGender 來寫
可是出現 `Method Encore\Admin\Grid::__toString() must not throw an exception, caught Error: Class 'App\Admin\Controllers\UserGender' not found`
是不是我需要 publish 一些東西出來？

**Comment by z-song** [comment]
加
```php
use App\Admin\Extensions\Tools\ UserGender;
```

**Comment by JackKuo-tw** [comment]
謝謝你這麼快回應我，成功囉！！！
